### ISSUE TITLE
autotest no longer works with rubygems 2.0

### ISSUE THREAD

**Issue by jdee** [seattlerb/zentest#45]
I see this:

```
/Users/jdee/.rvm/gems/ruby-2.0.0-p247/gems/ZenTest-4.4.2/lib/autotest.rb:221:in `autodiscover': undefined method `source_index' for Gem:Module (NoMethodError)
    from /Users/jdee/.rvm/gems/ruby-2.0.0-p247/gems/ZenTest-4.4.2/lib/autotest.rb:145:in `runner'
    from /Users/jdee/.rvm/gems/ruby-2.0.0-p247/gems/ZenTest-4.4.2/bin/autotest:7:in `<top (required)>'
    from /Users/jdee/.rvm/gems/ruby-2.0.0-p247/bin/autotest:23:in `load'
    from /Users/jdee/.rvm/gems/ruby-2.0.0-p247/bin/autotest:23:in `<main>'
    from /Users/jdee/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/jdee/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```

And

http://stackoverflow.com/questions/15349869/undefined-method-source-index-for-gemmodule-nomethoderror

Indicates that Gem.source_index was removed in rubygems 2.0.

Apologies if this is a dupe. I didn't see another issue for this.
