### ISSUE TITLE
NoMethodError: undefined method `maglev?'

### ISSUE THREAD

**Issue by voxik** [seattlerb/zentest#34]
I observe the following test error:

```
  1) Error:
test_testcase9(TestZenTest):
NoMethodError: undefined method `maglev?' for #<TestZenTest:0x000000017680d0>
    /builddir/build/BUILD/rubygem-ZenTest-4.9.0/usr/share/gems/gems/ZenTest-4.9.0/test/test_zentest.rb:559:in `test_testcase9'
105 tests, 262 assertions, 0 failures, 1 errors, 0 skips
ruby -v: ruby 2.0.0dev (2013-02-14 trunk 39237) [x86_64-linux]
```

Seems to be caused by 6c96ec85bac6c7c8d505e3e248134d32bbbc8c9d. Not sure where the #magev? method should come from.
